name: Build, Test & Publish

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    uses: pygmystack/.github/workflows/container-build-test-publish.yml@main
    with:
      image_name: mailhog
      replace_source: ghcr.io/pygmystack/mailhog:main
      oc_authors: the pygmy stack, Ian Kent (MailHog)
      oc_description: MailHog mail testing, configured for use with the pygmy stack
      extra_pull_images: uselagoon/php-8.5-fpm
    secrets: inherit
